site_name: TRM Knowledge Base (Beta)
site_url: https://s1trm.github.io/knowledge
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    # - primary: black
    # - accent: yellow
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  logo: assets/logo.png

plugins:
  - search

nav:
  - Pedoman Akademik:
    - pedak_2024.md

  - Proyek Akhir:
    - panduan_penyelesaian_tugas_akhir.md
    - kriteria_tambahan_summa_cumlaude.md
    - persyaratan_kelulusan_dan_standar_tugas_akhir.md
    - judul_pa.md
    - prosedur_pa.md

  - SKPI:
    - skpi_2022.md

  - TAK:
    - tak.md
    # - sptjm.md

  - Kurikulum:
    - plo.md
    - clo_plo.md

  - Rekognisi:
    - panduan_rekognisi.md
  # - FAQ: faq.md
    

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - admonition

