site_name: TRM Knowledge Base
site_url: https://s1trm.github.io/knowledge
theme:
  name: material
  palette:
    primary: black
    accent: yellow
  features:
    - search.suggest
    - search.highlight

plugins:
  - search

nav:
  - pedak_2024.md

  - Proyek Akhir:
    - panduan_penyelesaian_tugas_akhir.md
    - kriteria_tambahan_summa_cumlaude.md
    - persyaratan_kelulusan_dan_standar_tugas_akhir.md
    - skpi_2022.md

  - tak.md
    # - sptjm.md

  - Kurikulum:
    - plo.md
    - clo_plo.md

  - Rekognisi:
    - panduan_rekognisi.md
  # - FAQ: faq.md
    
