site_name: TRM Knowledge Base (Beta)
site_url: https://s1trm.github.io/knowledge
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    # - primary: black
    # - accent: yellow
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  logo: assets/logo.png

plugins:
  - search

nav:
  - Keuangan:
    - pembayaran_bpp.md
    - bpp_bni.md

  - Kurikulum:
    - daftar_mk.md  
    - plo.md
    - clo_plo.md

  - Lain-Lain:
    - gedung.md

  - Magang:
    - magang.md

  - Akademik:
    - Kalender Akademik: kaldik.md
    - Pedoman Akademik 2026: pedak_2026.md
    - Pedoman Akademik 2024: pedak_2024.md

  - Rekognisi:
    - panduan_rekognisi.md

  - SKPI:
    - skpi_2022.md

  - Surat-Menyurat:
    - cuti.md
    - surat.md
    - undur_diri.md
    - sbkp.md

  - TAK:
    - tak.md
    - tak_lms.md
    - submit_tak.md
    - star.md

  - Tugas Akhir (TA):
    - panduan_penyelesaian_tugas_akhir.md
    - kriteria_tambahan_summa_cumlaude.md
    - persyaratan_kelulusan_dan_standar_tugas_akhir.md
    - sptjm.md
    - judul_pa.md
    - prosedur_pa.md
    - template_pa.md
    - jalur_pa.md
    - pa_publikasi.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - admonition
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css: []

